AWSTemplateFormatVersion: '2010-09-09'
Description: Sample CloudFormation template for deploying AWS infrastructure.

Parameters:

  VpcCIDR:
    Type: String
    Default: 10.0.0.0/16

  PublicSubnetCIDR:
    Type: String
    Default: 10.0.1.0/24

  InstanceType:
    Type: String
    Default: t2.micro

  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:

  SampleVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR

Outputs:

  VPCID:
    Description: Created VPC ID
    Value: !Ref SampleVPC
